# Generated by Django 5.2.7 on 2025-11-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnershiprequest',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
