# Generated by Django 5.2.7 on 2025-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityFourthSectionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='quality/')),
                ('title', models.CharField(max_length=200)),
                ('titleSpan', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('mainTitleSpan1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('mainTitleSpan2', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('leftSideImage1', models.ImageField(upload_to='quality/')),
                ('leftSideImage2', models.ImageField(upload_to='quality/')),
                ('leftSideImage3', models.ImageField(upload_to='quality/')),
                ('rightSideImage', models.ImageField(upload_to='quality/')),
            ],
        ),
        migrations.CreateModel(
            name='QualitySecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality/')),
                ('title', models.CharField(max_length=200)),
                ('titleSpan', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityThirdSectionDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality/')),
                ('dropsTitle', models.CharField(max_length=200)),
                ('dropsText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityThirdSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropsList', models.ManyToManyField(related_name='third_sections', to='quality.qualitythirdsectiondrop')),
            ],
        ),
    ]
