# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_qualityfourthsectionblock_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityfourthsectionblock',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualityfourthsectionblock',
            name='titleSpan_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualityfourthsectionblock',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualityherosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualityherosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualityherosection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualityherosection',
            name='title1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualityherosection',
            name='title2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualitysecondsection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualitysecondsection',
            name='titleSpan_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualitysecondsection',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
