# Generated by Django 5.2.7 on 2025-11-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_qualityfourthsectionblock_text_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfourthsectionblock',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan1_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='mainTitleSpan2_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title1_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualityherosection',
            name='title2_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='titleSpan_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitysecondsection',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsText_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitythirdsectiondrop',
            name='dropsTitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
