# Generated by Django 5.2.7 on 2025-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FourthSectionGrowTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('title', models.CharField(max_length=200)),
                ('titleSpan', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('mainTitleSpan1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('mainTitleSpan2', models.CharField(max_length=200)),
                ('leftSideImage', models.ImageField(upload_to='products/')),
                ('rightSideImage1', models.ImageField(upload_to='products/')),
                ('rightSideImage2', models.ImageField(upload_to='products/')),
                ('rightSideImage3', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondSectionSmallCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('titleSpan', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSectionBigCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('titleSpan', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(related_name='second_sections', to='products.secondsectionsmallcard')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigCard', models.ManyToManyField(related_name='third_sections', to='products.thirdsectionbigcard')),
            ],
        ),
    ]
