# Generated by Django 5.2.7 on 2025-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='titleSpan_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='titleSpan_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='titleSpan_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='titleSpan_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='titleSpan_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='titleSpan_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='titleSpan_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='titleSpan_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='titleSpan_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='titleSpan_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
