# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fourthsectiongrowtogether_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='titleSpan_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='titleSpan_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectionbigcard',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
