# Generated by Django 5.2.7 on 2025-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_littleimages_alter_fourthsectiongrowtogether_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondsectionsmallcard',
            name='littleImages',
        ),
        migrations.AddField(
            model_name='secondsectionsmallcard',
            name='littleImages',
            field=models.ManyToManyField(blank=True, related_name='small_cards', to='products.littleimages'),
        ),
    ]
