# Generated by Django 5.2.7 on 2025-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_files_page_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='shop.files'),
        ),
        migrations.AlterField(
            model_name='element',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='element',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
    ]
