# Generated by Django 5.2.7 on 2025-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_element_files_alter_element_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html_content', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='files',
        ),
        migrations.RemoveField(
            model_name='element',
            name='page',
        ),
        migrations.RemoveField(
            model_name='element',
            name='products',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
