# Generated by Django 5.2.7 on 2025-10-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contentblock_remove_element_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Заголовок'), (1, 'Отзывы'), (2, 'Баннер / главный блок'), (3, 'Страны'), (4, 'Продукты'), (5, 'Матрешки'), (6, 'Доп блоки')], null=True, verbose_name='Тип элемента')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='Видео/Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
        migrations.AddField(
            model_name='element',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='shop.files'),
        ),
        migrations.AddField(
            model_name='element',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='shop.page'),
        ),
        migrations.AddField(
            model_name='element',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
    ]
