# Generated by Django 5.2.7 on 2025-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('titleSpan1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('titleSpan2', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image1', models.ImageField(upload_to='factory/')),
                ('image2', models.ImageField(upload_to='factory/')),
                ('image3', models.ImageField(upload_to='factory/')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='factory/')),
            ],
        ),
        migrations.CreateModel(
            name='SwiperSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='factory/')),
                ('alt', models.CharField(max_length=200)),
            ],
        ),
    ]
