# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_herosection_text_en_herosection_text_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='titleSpan1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='titleSpan2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='swiperslide',
            name='alt_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
