# Generated by Django 5.2.7 on 2025-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReachUsHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('leftSideImage1', models.ImageField(upload_to='reachus/')),
                ('leftSideImage2', models.ImageField(upload_to='reachus/')),
                ('leftSideImage3', models.ImageField(upload_to='reachus/')),
                ('rightSideImage', models.ImageField(upload_to='reachus/')),
            ],
        ),
        migrations.CreateModel(
            name='ReachUsSecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='reachus/')),
            ],
        ),
    ]
