# Generated by Django 5.2.7 on 2025-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachusherosection',
            name='mainTitle_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='mainTitle_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='mainTitle_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='mainTitle_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='mainTitle_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
