# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachUs', '0002_reachusherosection_maintitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachusherosection',
            name='mainTitle_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reachusherosection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reachussecondsection',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
