# Generated by Django 5.2.7 on 2025-11-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('mainTitleSpan1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('mainTitleSpan2', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('leftSideImage1', models.ImageField(upload_to='about/hero/')),
                ('leftSideImage2', models.ImageField(upload_to='about/hero/')),
                ('leftSideImage3', models.ImageField(upload_to='about/hero/')),
                ('rightSideImage', models.ImageField(upload_to='about/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(max_length=255)),
                ('mainTitleSpan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DropsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/drops/')),
                ('dropsTitle', models.CharField(max_length=255)),
                ('dropsText', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropsList', to='aboutUs.secondsection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CountryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/countries/')),
                ('innerTitle', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='aboutUs.secondsection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ThirdBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('titleSpan', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='about/third/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='aboutUs.thirdsection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
