# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_countryitem_innertitle_en_countryitem_innertitle_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryitem',
            name='innerTitle_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='countryitem',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dropsitem',
            name='dropsText_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dropsitem',
            name='dropsTitle_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitleSpan_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thirdblock',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdblock',
            name='titleSpan_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thirdblock',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
