# Generated by Django 5.2.7 on 2025-11-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_countryitem_innertitle_tr_countryitem_text_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='innerTitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryitem',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsText_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropsitem',
            name='dropsTitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitleSpan_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='titleSpan_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
