# Generated by Django 5.2.7 on 2025-10-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoreviews',
            options={'verbose_name': 'Видео отзыв', 'verbose_name_plural': 'Видео отзывы'},
        ),
    ]
