# Generated by Django 5.2.7 on 2025-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsection',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='titleSpan_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='titleSpan_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='titleSpan_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='titleSpan_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='titleSpan_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='firstText_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='firstText_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='firstText_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='firstText_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='firstText_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitle_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitle_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitle_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitle_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitle_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondText_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondText_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondText_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondText_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondText_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectioncard',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectioncard',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectioncard',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectioncard',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdsectioncard',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
