# Generated by Django 5.2.7 on 2025-11-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_herosection_title1_herosection_title1_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='reviews/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videoId', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
