# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='titleSpan_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='titleSpan_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourthsectiongrowtogether',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='firstText_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mainTitle_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondText_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title1_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title2_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='mainTitle_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsectioncard',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdsectioncard',
            name='text_tr',
            field=models.TextField(null=True),
        ),
    ]
