# Generated by Django 5.2.7 on 2025-11-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_firstsection_text_tr_firstsection_titlespan_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fourthsectiongrowtogether',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='firstText_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan1_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitleSpan2_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='mainTitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondText_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='mainTitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectioncard',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdsectioncard',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
