# Generated by Django 5.2.7 on 2025-11-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(max_length=200)),
                ('titleSpan1', models.CharField(max_length=200)),
                ('titleSpan2', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('leftSideImage1', models.ImageField(upload_to='news/')),
                ('leftSideImage2', models.ImageField(upload_to='news/')),
                ('leftSideImage3', models.ImageField(upload_to='news/')),
                ('rightSideImage', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSecondBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('titleSpan', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstBlock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_block', to='news.newssecondblock')),
                ('secondBlock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_block', to='news.newssecondblock')),
                ('thirdBlock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='third_block', to='news.newssecondblock')),
            ],
        ),
    ]
