# Generated by Django 5.2.7 on 2025-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsherosection',
            name='mainTitle_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='mainTitle_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='mainTitle_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='mainTitle_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='mainTitle_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan1_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan1_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan1_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan1_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan2_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan2_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan2_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan2_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='titleSpan_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='titleSpan_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='titleSpan_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='titleSpan_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='titleSpan_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
