# Generated by Django 5.2.7 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsherosection_maintitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsherosection',
            name='mainTitle_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan1_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsherosection',
            name='titleSpan2_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='titleSpan_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newssecondblock',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
