# Generated by Django 5.2.7 on 2025-11-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsherosection_maintitle_tr_newsherosection_text_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='mainTitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan1_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsherosection',
            name='titleSpan2_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssecondblock',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
